const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  platform: process.platform, 
  relaunchAsAdmin: () => ipcRenderer.invoke('app:relaunchAsAdmin'),
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  loadAccounts: () => ipcRenderer.invoke('accounts:load'),
  addAccount: (a) => ipcRenderer.invoke('accounts:add', a),
  removeAccount: (id) => ipcRenderer.invoke('accounts:remove', id),
  updateAccount: (id, data) => ipcRenderer.invoke('accounts:update', id, data),
  reorderAccounts: (ids) => ipcRenderer.invoke('accounts:reorder', ids),
  saveAccounts: (list) => ipcRenderer.invoke('accounts:save', list),
  loadPackages: () => ipcRenderer.invoke('packages:load'),
  savePackages: (packages) => ipcRenderer.invoke('packages:save', packages),
  generateBloxGenAccount: (apiKey) => ipcRenderer.invoke('bloxgen:generateAccount', apiKey),
  openLogin: () => ipcRenderer.invoke('roblox:openLogin'),
  openBrowserWithCookie: (cookie, targetUrl) => ipcRenderer.invoke('roblox:openBrowserWithCookie', { cookie, targetUrl }),
  cancelLogin: () => ipcRenderer.send('login:cancel'),
  validateCookie: (cookie) => ipcRenderer.invoke('roblox:validateCookie', cookie),
  setRobloxVolume: (percent) => ipcRenderer.invoke('roblox:setVolume', percent),
  killAllRoblox: () => ipcRenderer.invoke('roblox:killAll'),
  killOneRoblox: (id) => ipcRenderer.invoke('roblox:killOne', id),
  getRunningCount: () => ipcRenderer.invoke('roblox:runningCount'),
  getTempSessions: () => ipcRenderer.invoke('roblox:tempSessions'),
  killTemp: (pid) => ipcRenderer.invoke('roblox:killTemp', pid),
  addTempSession: (pid) => ipcRenderer.invoke('roblox:addTempSession', pid),
  refreshCookieFromStore: (accountId, userId) => ipcRenderer.invoke('roblox:refreshCookieFromStore', accountId, userId),
  changePassword: (accountId, cookie, currentPassword, newPassword) => ipcRenderer.invoke('roblox:changePassword', accountId, cookie, currentPassword, newPassword),
  reloginHeadless: (username, password) => ipcRenderer.invoke('roblox:reloginHeadless', username, password),
  getPresence: (userIds) => ipcRenderer.invoke('roblox:presence', userIds),
  onAllRobloxClosed: (cb) => ipcRenderer.on('roblox:allClosed', () => cb()),
  launchRoblox: (id, cookie, target, versionHash, options) => ipcRenderer.invoke('roblox:launch', id, cookie, target, versionHash, options),
  getInstalledVersions: () => ipcRenderer.invoke('roblox:getInstalledVersions'),
  removeRobloxVersion: (hash) => ipcRenderer.invoke('roblox:removeVersion', hash),
  getVersionsDiskUsage: () => ipcRenderer.invoke('roblox:getVersionsDiskUsage'),
  cleanOldVersions: (keepHashes) => ipcRenderer.invoke('roblox:cleanOldVersions', keepHashes),
  openRobloxVersionDirectory: (hash) => ipcRenderer.invoke('roblox:openVersionDirectory', hash),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: (data) => ipcRenderer.invoke('settings:save', data),
  encStatus: () => ipcRenderer.invoke('enc:status'),
  encUnlock: (pass) => ipcRenderer.invoke('enc:unlock', pass),
  encSetKey: (pass) => ipcRenderer.invoke('enc:setKey', pass),
  multiInstanceStatus: () => ipcRenderer.invoke('multiinstance:status'),
  antiAfkStatus: () => ipcRenderer.invoke('antiafk:status'),
  readFFlags: () => ipcRenderer.invoke('fflag:read'),
  writeFFlags: (flags) => ipcRenderer.invoke('fflag:write', flags),
  readFpsCap: () => ipcRenderer.invoke('fps:read'),
  writeFpsCap: (cap) => ipcRenderer.invoke('fps:write', cap),
  onChromeProgress: (cb) => ipcRenderer.on('chrome:download-progress', (_, data) => cb(data)),
  onRddDownloadProgress: (cb) => ipcRenderer.on('rdd:download-progress', (_, data) => cb(data)),
  onRobloxClosed: (cb) => ipcRenderer.on('roblox:closed', (_, id) => cb(id)),
  onLaunchVerifyFail: (cb) => ipcRenderer.on('launch:verify-fail', (_, data) => cb(data)),
  onRobloxCount: (cb) => ipcRenderer.on('roblox:count', (_, n) => cb(n)),
  onTempSessions: (cb) => ipcRenderer.on('roblox:temp', (_, list) => cb(list)),
  onRamStats: (cb) => ipcRenderer.on('roblox:ram-stats', (_, stats) => cb(stats)),
  onLogEntry: (cb) => ipcRenderer.on('log:entry', (_, data) => cb(data)),
  getRobloxVersion: () => ipcRenderer.invoke('roblox:getVersion'),
  getGameName: (placeId, cookie) => ipcRenderer.invoke('roblox:getGameName', placeId, cookie),

  runSwap: (opts) => ipcRenderer.invoke('swap:run', opts),
  onSwapLog: (cb) => ipcRenderer.on('swap:log', (_, data) => cb(data)),
  onSwapStatus: (cb) => ipcRenderer.on('swap:status', (_, data) => cb(data)),
  onSwapComplete: (cb) => ipcRenderer.on('swap:complete', (_, data) => cb(data)),

  getAdapters: () => ipcRenderer.invoke('mac:getAdapters'),
  spoofMac: (desc, mac) => ipcRenderer.invoke('mac:spoof', desc, mac),
  resetMac: (desc) => ipcRenderer.invoke('mac:reset', desc),
  restartAdapter: (name) => ipcRenderer.invoke('mac:restartAdapter', name),
  dhcpRefresh: () => ipcRenderer.invoke('mac:dhcpRefresh'),

  hwidIsElevated: () => ipcRenderer.invoke('hwid:isElevated'),
  detectAnticheat: () => ipcRenderer.invoke('hwid:detectAnticheat'),
  createRestorePoint: (desc) => ipcRenderer.invoke('hwid:restorePoint', desc),
  hwidBackupExists: () => ipcRenderer.invoke('hwid:backupExists'),
  hwidBackupInfo: () => ipcRenderer.invoke('hwid:backupInfo'),
  backupHwid: () => ipcRenderer.invoke('hwid:backup'),
  spoofHwid: (opts) => ipcRenderer.invoke('hwid:spoof', opts),
  restoreHwid: (opts) => ipcRenderer.invoke('hwid:restore', opts),
  purgeRoblox: () => ipcRenderer.invoke('hwid:purgeRoblox'),

  rddGetVersion: (channel, binaryType) => ipcRenderer.invoke('rdd:getVersion', channel, binaryType),
  rddSaveExtractedBatch: (versionHash, files) => ipcRenderer.invoke('rdd:saveExtractedBatch', versionHash, files),
  rddSaveExtractedFile: (versionHash, relPath, base64Data) => ipcRenderer.invoke('rdd:saveExtractedFile', versionHash, relPath, base64Data),

  weaoVersions: (which) => ipcRenderer.invoke('weao:versions', which),
  weaoExploits: () => ipcRenderer.invoke('weao:exploits'),
  pickExecutor: () => ipcRenderer.invoke('executor:pick'),

  getProtocolStatus: () => ipcRenderer.invoke('protocol:status'),
  registerProtocol: () => ipcRenderer.invoke('protocol:register'),
  removeProtocol: () => ipcRenderer.invoke('protocol:remove'),

});
